-- 2026-09-01-product-release-stage-and-marketing.sql
-- Stage 1(产品化升级):产品成熟度轴 release_stage(正式版/公测版/开发中)+ 营销内容 marketing(jsonb)
--   + 现有产品营销回填 + 把 12 个开发中智能体从「website 写死」迁为真产品行(release_stage=developing)。
-- 幂等:列用 IF NOT EXISTS、CHECK 用 DO 卫、INSERT 用 ON CONFLICT DO NOTHING。
BEGIN;

-- ① 成熟度轴 release_stage(与 status/visibility/type/origin 正交)。
--    存量都是已上线 → 默认 'ga' 回填;之后新产品默认 'developing'(未成熟)。
ALTER TABLE product.products ADD COLUMN IF NOT EXISTS release_stage varchar(16) NOT NULL DEFAULT 'ga';
ALTER TABLE product.products ALTER COLUMN release_stage SET DEFAULT 'developing';
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'product.products'::regclass AND conname = 'chk_products_release_stage'
  ) THEN
    ALTER TABLE product.products
      ADD CONSTRAINT chk_products_release_stage CHECK (release_stage IN ('ga','beta','developing'));
  END IF;
END $$;
CREATE INDEX IF NOT EXISTS idx_products_release_stage ON product.products (release_stage);

-- ② 营销内容 marketing(jsonb,双语富结构 {zh|en:{tagline,value,highlights[],tags[],industries[],detail}})。
ALTER TABLE product.products ADD COLUMN IF NOT EXISTS marketing jsonb;

-- ③ 列锁:platform_svc 可写新列(与 40/98 GRANT 白名单同步)。
GRANT UPDATE (release_stage, marketing) ON product.products TO platform_svc;

-- ④ 现有产品营销回填(value 从官网写死迁入;仅当 marketing 尚空)。
UPDATE product.products SET marketing = '{"zh":{"tagline":"L2 · 数据智能","value":"让数据可治理、可信赖、可复用，为上层智能应用提供高质量数据供给。","highlights":[],"tags":[],"industries":[],"detail":""},"en":{"tagline":"L2 · Data intelligence","value":"Make data governable, trustworthy and reusable — high-quality supply for every intelligent app above.","highlights":[],"tags":[],"industries":[],"detail":""}}'::jsonb WHERE product_code = 'arda' AND marketing IS NULL;
UPDATE product.products SET marketing = '{"zh":{"tagline":"L1 · 模型底座","value":"把大模型能力沉淀为企业可控、可复用的模型服务底座。","highlights":[],"tags":[],"industries":[],"detail":""},"en":{"tagline":"L1 · Model foundation","value":"Turn large-model capability into a controllable, reusable model foundation.","highlights":[],"tags":[],"industries":[],"detail":""}}'::jsonb WHERE product_code = 'atlas' AND marketing IS NULL;
UPDATE product.products SET marketing = '{"zh":{"tagline":"L1 · 能力编排","value":"以搭积木的方式快速组装 AI 应用，缩短从能力到业务的路径。","highlights":[],"tags":[],"industries":[],"detail":""},"en":{"tagline":"L1 · Ability orchestration","value":"Assemble AI apps like building blocks — shorten the path from capability to business.","highlights":[],"tags":[],"industries":[],"detail":""}}'::jsonb WHERE product_code = 'runos' AND marketing IS NULL;
UPDATE product.products SET marketing = '{"zh":{"tagline":"L2 · 知识智能","value":"把散落的企业知识变成可检索、可推理的智能资产。","highlights":[],"tags":[],"industries":[],"detail":""},"en":{"tagline":"L2 · Knowledge intelligence","value":"Turn scattered enterprise knowledge into retrievable, reasoning-ready assets.","highlights":[],"tags":[],"industries":[],"detail":""}}'::jsonb WHERE product_code = 'karda' AND marketing IS NULL;

-- ⑤ 12 个开发中智能体入库(草稿名沿用备份;release_stage=developing;is_customer_visible=true
--    上站——本 PR 同时上线 website 三态渲染,广场按 release_stage 显示「开发中」徽标+敬请期待;
--    ON CONFLICT 幂等)。营销内容含能力/标签/行业(备份全字段)。
INSERT INTO product.products
  (id, product_code, product_type, category_id, product_name, product_nick, description, description_key, tags, release_stage, status, is_customer_visible, is_workforce_visible, origin, marketing)
VALUES
  (gen_random_uuid(), 'contractaudit', 'general_agent', 1, '合同审核智能体', 'Contract Review Agent', '面向采购、销售、法务和项目管理场景，自动识别合同条款风险、缺失条款、履约节点和审批关注点。', 'product.product.contractaudit.desc', ARRAY['大模型','知识库','合规审查']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"数字员工 · 通用类","value":"减少人工逐条审阅成本，让业务部门在提交审批前就能得到结构化风险提示。","highlights":["条款风险识别","标准模板比对","审批意见生成"],"tags":["大模型","知识库","合规审查"],"industries":["general","legal"],"detail":""},"en":{"tagline":"Digital Employee · General","value":"Reduces manual review effort and gives business teams structured risk hints before approval submission.","highlights":["Clause risk detection","Template comparison","Approval comment drafting"],"tags":["LLM","Knowledge Base","Compliance Review"],"industries":["general","legal"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'digitallegal', 'general_agent', 1, '数字法务智能体', 'Digital Legal Agent', '沉淀企业制度、法律法规、历史案件和问答知识，为员工提供法务咨询、制度检索和材料草拟支持。', 'product.product.digitallegal.desc', ARRAY['大模型问答','RAG','企业知识']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"数字员工 · 通用类","value":"把常见法务咨询从人工响应转为自助问答，并保留引用来源与审核链路。","highlights":["法规制度问答","函件草拟","风险解释与引用追溯"],"tags":["大模型问答","RAG","企业知识"],"industries":["general","legal"],"detail":""},"en":{"tagline":"Digital Employee · General","value":"Turns common legal questions into self-service answers while keeping citations and review trails.","highlights":["Policy Q&A","Legal letter drafting","Risk explanation with citations"],"tags":["LLM Q&A","RAG","Enterprise Knowledge"],"industries":["general","legal"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'bizinsight', 'general_agent', 1, '经营分析智能体', 'Business Analysis Agent', '连接经营指标、财务数据、客户数据和项目进度，自动生成经营日报、异常提醒和归因分析。', 'product.product.bizinsight.desc', ARRAY['智能数据','指标体系','BI Agent']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"数字员工 · 通用类","value":"让管理者从看报表转向问业务，快速定位收入、成本、交付和客户变化背后的原因。","highlights":["指标问答","异常归因","经营报告生成"],"tags":["智能数据","指标体系","BI Agent"],"industries":["general","operations"],"detail":""},"en":{"tagline":"Digital Employee · General","value":"Helps managers move from reading dashboards to asking business questions and finding root causes faster.","highlights":["Metric Q&A","Anomaly attribution","Business report generation"],"tags":["Intelligent Data","Metrics","BI Agent"],"industries":["general","operations"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'wargaming', 'industry_agent', 1, '战场推演智能体', 'Battlefield Simulation Agent', '面向复杂态势推演、资源约束评估和方案比选，构建可解释、可复盘的沙盘推演辅助能力。', 'product.product.wargaming.desc', ARRAY['数字孪生','仿真推演','智能体协同']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 推演仿真","value":"帮助业务团队在安全边界内进行态势模拟和方案评估，提升推演效率和复盘质量。","highlights":["态势要素建模","方案比选推演","推演过程复盘"],"tags":["数字孪生","仿真推演","智能体协同"],"industries":["defense"],"detail":""},"en":{"tagline":"Industry Agent · Simulation","value":"Helps teams run situation simulation and plan evaluation within safety boundaries, improving simulation efficiency and review quality.","highlights":["Situation element modeling","Plan comparison simulation","Process review"],"tags":["Digital Twin","Simulation","Agent Collaboration"],"industries":["defense"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'dronemonitor', 'industry_agent', 1, '无人机监测智能体', 'Drone Monitoring Agent', '对接无人机巡检影像、飞行任务、空间网格和告警规则，自动识别异常点并生成巡检报告。', 'product.product.dronemonitor.desc', ARRAY['具身智能','视觉识别','空间数据']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 低空巡检","value":"把无人机采集的数据转化为可分派的任务和可追踪的处置闭环。","highlights":["影像异常识别","巡检路线摘要","告警任务派发"],"tags":["具身智能","视觉识别","空间数据"],"industries":["lowAltitude","emergency","industry"],"detail":""},"en":{"tagline":"Industry Agent · Low-altitude","value":"Turns drone-collected data into assignable tasks and traceable response loops.","highlights":["Image anomaly detection","Inspection route summary","Alert task dispatch"],"tags":["Embodied AI","Vision","Spatial Data"],"industries":["lowAltitude","emergency","industry"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'datagovernance', 'industry_agent', 1, '数据治理智能体', 'Data Governance Agent', '面向数据资产盘点、质量检查、口径解释和血缘分析，辅助企业持续建设智能数据底座。', 'product.product.datagovernance.desc', ARRAY['智能数据','元数据','数据质量']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 数据治理","value":"降低数据治理门槛，让业务人员也能理解数据来源、质量问题和指标口径。","highlights":["数据资产问答","质量规则建议","指标口径解释"],"tags":["智能数据","元数据","数据质量"],"industries":["data","general","industry"],"detail":""},"en":{"tagline":"Industry Agent · Data Governance","value":"Lowers the barrier to data governance so business users can understand data sources, quality issues, and metric definitions.","highlights":["Data asset Q&A","Quality rule suggestions","Metric definition explanation"],"tags":["Intelligent Data","Metadata","Data Quality"],"industries":["data","general","industry"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'emergencyops', 'industry_agent', 1, '应急指挥智能体', 'Emergency Command Agent', '围绕突发事件态势汇聚、预案匹配、资源调度和任务跟踪，为指挥中心提供连续辅助。', 'product.product.emergencyops.desc', ARRAY['大模型研判','调度智能体','数字孪生']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 应急管理","value":"把事件摘要、处置建议、队伍物资状态和回执统一到一条指挥链路。","highlights":["事件摘要","预案匹配","任务闭环跟踪"],"tags":["大模型研判","调度智能体","数字孪生"],"industries":["emergency"],"detail":""},"en":{"tagline":"Industry Agent · Emergency","value":"Unifies event summaries, response suggestions, team and supply status, and acknowledgements into one command chain.","highlights":["Event summary","Plan matching","Task loop tracking"],"tags":["LLM Assessment","Dispatch Agent","Digital Twin"],"industries":["emergency"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'urbanrisk', 'industry_agent', 1, '城市风险研判智能体', 'Urban Risk Assessment Agent', '整合人口、车辆、场所、事件和风险源数据，持续发现城市公共安全和治理风险。', 'product.product.urbanrisk.desc', ARRAY['智能数据','知识图谱','风险研判']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 城市治理","value":"把跨部门线索转为可解释的风险清单和空间态势，辅助提前干预。","highlights":["多源线索融合","风险关联分析","空间态势展示"],"tags":["智能数据","知识图谱","风险研判"],"industries":["emergency","data"],"detail":""},"en":{"tagline":"Industry Agent · Urban Governance","value":"Turns cross-agency clues into explainable risk lists and spatial situation views for earlier intervention.","highlights":["Multi-source clue fusion","Risk relationship analysis","Spatial situation display"],"tags":["Intelligent Data","Knowledge Graph","Risk Assessment"],"industries":["emergency","data"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'equipinspect', 'industry_agent', 1, '工业设备巡检智能体', 'Industrial Equipment Inspection Agent', '连接设备传感、巡检记录、维修工单和专家知识，识别设备异常趋势并建议处置动作。', 'product.product.equipinspect.desc', ARRAY['工业智能体','IoT','预测维护']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 工业制造","value":"帮助工厂从定期巡检走向预测性维护，减少停机和重复排查。","highlights":["异常趋势识别","维修知识检索","工单建议生成"],"tags":["工业智能体","IoT","预测维护"],"industries":["industry"],"detail":""},"en":{"tagline":"Industry Agent · Manufacturing","value":"Helps factories move from scheduled inspection to predictive maintenance, reducing downtime and repeated diagnosis.","highlights":["Abnormal trend detection","Maintenance knowledge retrieval","Work order suggestion"],"tags":["Industrial Agent","IoT","Predictive Maintenance"],"industries":["industry"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'bidproposal', 'general_agent', 1, '标书方案智能体', 'Proposal Writing Agent', '基于企业知识库、产品资料和历史投标文件，辅助生成方案大纲、响应点和差异化亮点。', 'product.product.bidproposal.desc', ARRAY['大模型写作','知识库','售前协同']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"数字员工 · 通用类","value":"让售前团队快速形成可编辑初稿，把时间投入到客户洞察和方案打磨上。","highlights":["招标文件解析","方案大纲生成","响应点检查"],"tags":["大模型写作","知识库","售前协同"],"industries":["general","operations"],"detail":""},"en":{"tagline":"Digital Employee · General","value":"Lets presales teams create editable drafts quickly and spend more time on customer insight and solution refinement.","highlights":["Bid document parsing","Proposal outline generation","Response point checking"],"tags":["LLM Writing","Knowledge Base","Presales"],"industries":["general","operations"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'supplychain', 'industry_agent', 1, '供应链协同智能体', 'Supply Chain Collaboration Agent', '连接采购、库存、物流、供应商和交付节点，监控异常并辅助生成协同处置建议。', 'product.product.supplychain.desc', ARRAY['智能数据','流程智能体','经营协同']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 经营协同","value":"提前发现交付风险，把跨部门沟通变成可跟踪的任务流。","highlights":["供应风险预警","库存与交付分析","协同任务生成"],"tags":["智能数据","流程智能体","经营协同"],"industries":["operations","industry"],"detail":""},"en":{"tagline":"Industry Agent · Operations","value":"Finds delivery risks earlier and turns cross-team communication into trackable task flows.","highlights":["Supply risk warning","Inventory and delivery analysis","Collaboration task generation"],"tags":["Intelligent Data","Workflow Agent","Operations"],"industries":["operations","industry"],"detail":""}}'::jsonb),
  (gen_random_uuid(), 'lowaltitude', 'industry_agent', 1, '低空资源调度智能体', 'Low-altitude Resource Dispatch Agent', '围绕低空巡检、应急通信、物资配送和空域资源，辅助任务编排、资源匹配和执行跟踪。', 'product.product.lowaltitude.desc', ARRAY['具身智能','低空经济','调度智能体']::text[], 'developing', 'active', true, true, 'self', '{"zh":{"tagline":"强业务类 · 低空经济","value":"让低空资源从单次任务执行升级为可调度、可复盘、可协同的业务能力。","highlights":["任务编排","资源匹配","执行状态跟踪"],"tags":["具身智能","低空经济","调度智能体"],"industries":["lowAltitude","emergency"],"detail":""},"en":{"tagline":"Industry Agent · Low-altitude Economy","value":"Upgrades low-altitude resources from one-off task execution into schedulable, reviewable, and collaborative business capability.","highlights":["Mission orchestration","Resource matching","Execution status tracking"],"tags":["Embodied AI","Low-altitude Economy","Dispatch Agent"],"industries":["lowAltitude","emergency"],"detail":""}}'::jsonb)
ON CONFLICT (product_code) DO NOTHING;

COMMIT;
