#!/usr/bin/env bash
# deploy/scripts/34-provision-idp-internal-secret.sh
# 在主机上铸 IdP 内部面的钥匙：secrets/platform-idp-internal.env（IDP_INTERNAL_TOKEN）。
# @package  @vxture/repo
# @layer    Infrastructure
# @category deployment-script
# @author   AI-Generated
# @date     2026-10-04
#
# Run: CONFIRM_PROVISION_IDP_INTERNAL=yes bash scripts/34-provision-idp-internal-secret.sh
#
# 这把钥匙只开 auth-bff 的 /internal/*（运营账号 / 客户账号管理、step-up），只注入
# auth-bff / admin-bff / arche-bff / opera-bff 四个容器。它**不能**放进 12-generate：那份脚本
# 被两份审计禁含 `openssl rand`（它只能从 example 落 CHANGEME 占位）。全部部署脚本里只有
# 27-provision-client-secrets.sh 用 openssl rand，本脚本照它的规矩：0600、只打印路径不打印值。
#
# 两条断言，任一不过就什么都不写（值先生成到变量里，断言过了才落盘）：
#   1. 值 ≠ platform.env 的 AUTH_INTERNAL_TOKEN —— 相同就是把拆分做成了空操作，产品手里的
#      值仍然开得了运营管理面；主机审计（39-audit-env 跨文件断言）与 41-verify 也盯这一条。
#   2. 值是 32 位 hex（`openssl rand -hex 16`，docs/10-standards/150-security.md §1.4 对
#      AUTH_INTERNAL_TOKEN 的同一条强度标准）。
#
# 幂等：文件已存在**且值是真值**即拒绝（exit 1，打印 `exists: <path>`），不覆盖。轮换用
# FORCE_PROVISION_IDP_INTERNAL=1，轮换后要重建四个容器（它们在容器启动时读 env_file）。
#
# **占位视同不存在**（打印 `placeholder: <path>`，不需要 FORCE）：12-generate 在每次
# 31-regular-upgrade（→ 13-prepare）里都会跑，而它会先从 example 落一个 CHANGEME 占位——
# 所以「切换日先派发 deploy、在 [1/4] 占位审计红了之后再跑本脚本」时文件已经在了。
# 这里若按「存在即拒绝」处理，owner 就被卡在两个拒绝之间（审计拒占位、本脚本拒覆盖）。
# 占位判据与 39-audit-env 的 isPlaceholder 同一套：空 / CHANGEME / CHANGE_ME / 两者前缀 /
# your- / change-me-。真值永远不被静默覆盖，这一条由 lib/provision-idp-internal.test.sh 钉住。
#
# 切换步骤见 docs/50-deployment/15-idp-internal-token-cutover.md。
set -euo pipefail

RUNTIME_DIR="${RUNTIME_DIR:-/srv/vxture/runtime}"
SECRETS_DIR="${SECRETS_DIR:-$RUNTIME_DIR/secrets}"
PLATFORM_ENV_FILE="${PLATFORM_ENV_FILE:-$SECRETS_DIR/platform.env}"
TARGET_FILE="${IDP_INTERNAL_ENV_FILE:-$SECRETS_DIR/platform-idp-internal.env}"
FORCE="${FORCE_PROVISION_IDP_INTERNAL:-0}"

if [ "${CONFIRM_PROVISION_IDP_INTERNAL:-}" != "yes" ]; then
  echo "错误：内部面钥匙 provision 只允许切换日或轮换时执行。" >&2
  echo "请确认后运行：CONFIRM_PROVISION_IDP_INTERNAL=yes bash scripts/34-provision-idp-internal-secret.sh" >&2
  exit 1
fi

# Read the raw value of KEY from an env file (empty if file or key absent).
read_kv() {
  local file="$1" key="$2" line
  [ -f "$file" ] || return 0
  line="$(grep -E "^${key}=" "$file" 2>/dev/null | tail -n 1 || true)"
  printf '%s' "${line#*=}"
}

echo "=== Vxture IdP Internal-Face Secret Provision ==="

if [ ! -f "$PLATFORM_ENV_FILE" ]; then
  echo "错误：缺少 $PLATFORM_ENV_FILE —— 没有它就断言不了「新值 ≠ AUTH_INTERNAL_TOKEN」，拒绝生成。" >&2
  exit 1
fi

# 占位判据（与 39-audit-env isPlaceholder 同一套）。去掉一层引号后判。
is_placeholder() {
  local v="$1"
  v="${v#\"}"; v="${v%\"}"; v="${v#\'}"; v="${v%\'}"
  case "$v" in
    ""|CHANGEME|CHANGE_ME|CHANGEME_*|CHANGE_ME_*|your-*|change-me-*) return 0 ;;
    *) return 1 ;;
  esac
}

if [ -f "$TARGET_FILE" ]; then
  CURRENT_VALUE="$(read_kv "$TARGET_FILE" IDP_INTERNAL_TOKEN)"
  if is_placeholder "$CURRENT_VALUE"; then
    # 12-generate 落的占位：视同不存在，铸真值，不需要 FORCE。
    echo "placeholder: $TARGET_FILE（IDP_INTERNAL_TOKEN 是空值或 CHANGEME 占位，视同不存在，铸真值）"
  elif [ "$FORCE" != "1" ]; then
    echo "exists: $TARGET_FILE"
    echo "（已有真值即不覆盖。轮换：FORCE_PROVISION_IDP_INTERNAL=1，然后重建 auth/admin/arche/opera 四个容器。）" >&2
    exit 1
  else
    echo "rotate: $TARGET_FILE（FORCE_PROVISION_IDP_INTERNAL=1：覆盖已有真值，之后要重建四个容器）"
  fi
fi

OLD_VALUE="$(read_kv "$PLATFORM_ENV_FILE" AUTH_INTERNAL_TOKEN)"
NEW_VALUE="$(openssl rand -hex 16)"

# 断言 2：32 位 hex。openssl 失常（输出空 / 短 / 带换行）在这里挡住，不落盘。
if ! printf '%s' "$NEW_VALUE" | grep -qE '^[0-9a-f]{32}$'; then
  echo "BAD value: generated token is not 32 hex chars (length ${#NEW_VALUE}); nothing written." >&2
  exit 1
fi

# 断言 1：不等于产品面的值。相等 = 拆分成空操作。
if [ -n "$OLD_VALUE" ] && [ "$NEW_VALUE" = "$OLD_VALUE" ]; then
  echo "BAD value: generated token equals AUTH_INTERNAL_TOKEN in $(basename "$PLATFORM_ENV_FILE"); nothing written." >&2
  exit 1
fi
if [ -z "$OLD_VALUE" ]; then
  echo "警告：$PLATFORM_ENV_FILE 没有 AUTH_INTERNAL_TOKEN，无法比对不等；继续生成（主机审计会在它就位后再比一次）。" >&2
fi

mkdir -p "$SECRETS_DIR"
umask 077
tmp="$(mktemp "$SECRETS_DIR/.platform-idp-internal.XXXXXX")"
{
  printf '# platform-idp-internal.env — IdP internal face only (auth-bff /internal/*).\n'
  printf '# Injected ONLY into auth-bff / admin-bff / arche-bff / opera-bff. Generated by 34-provision-idp-internal-secret.sh.\n'
  printf 'IDP_INTERNAL_TOKEN=%s\n' "$NEW_VALUE"
} > "$tmp"
chmod 600 "$tmp"
mv -f "$tmp" "$TARGET_FILE"
chmod 600 "$TARGET_FILE"

# Only the PATH is printed — never the value (keeps it out of CI logs / terminals).
echo "ok: $TARGET_FILE"
echo "下一步：按 docs/50-deployment/15-idp-internal-token-cutover.md 走 —— 合并 PR、出 tag、派发 deploy；"
echo "       旧容器不认识这个文件，先放着零影响。"
